trigger: none
pr: none

resources:
  repositories:
    - repository: devRepo
      type: github
      name: your-org/development-repo-name
      endpoint: your-github-service-connection
      trigger:
        tags:
          include:
            - '*'
        pullRequest:
          branches:
            include:
              - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - script: echo "Triggered by $(Build.SourceBranch)"
    displayName: "Show Branch Info"