trigger: none  # Disable default trigger for Devops-Repo itself

pr: none       # Disable PR triggers for Devops-Repo itself

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world
      ref: refs/heads/main
      endpoint: GitHub-Service-Connection of hello world dev repo
      trigger:
        tags:
          include:
            - '*'   # Trigger for any tag
        pullRequests:
          branches:
            include:
              - '*'   # Trigger for any PR to any branch

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Install and Build Next.js App'