trigger: none
pr: none

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world
      endpoint: svc_nodejs_repo
      trigger:
        tags:
          include:
            - '*'
        pullRequest:
          branches:
            include:
              - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - script: echo "Triggered by $(Build.SourceBranch)"
    displayName: "Show Branch Info"