trigger: none
pr: none

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world
      endpoint: svc_nodejs_repo
      trigger:
        tags:
          include:
            - '*'    # Trigger on any tag

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - script: echo "Triggered by tag: $(Build.SourceBranchName)"
    displayName: 'Show Tag Info'