trigger: none
pr: none

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world
      endpoint: svc_nodejs_repo
      trigger:
        branches:
          include:
            - '*'         # Trigger on any push or PR to any branch
        tags:
          include:
            - '*'         # Trigger on any tag

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
  
  - script: |
      echo "Triggered from branch or tag: $(Build.SourceBranch)"
    displayName: 'Show Trigger Info'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build Next.js App'