trigger: none  # We will manually or remotely trigger this

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world
      ref: main
      endpoint: GitHub-Service-Connection of hello world dev repo

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Install and Build Next.js App'