trigger: none     # No CI trigger for this repo
pr: none          # No PR trigger for this repo

resources:
  repositories:
    - repository: devRepo
      type: github
      name: RadhaKrishna98/next-js-hello-world  # ✅ EXACT GitHub repo name
      ref: refs/heads/main
      endpoint: svc_nodejs_repo      # ✅ Your Azure DevOps GitHub connection name
      trigger:
        tags:
          include:
            - '*'       # ✅ Trigger on any tag created in dev repo

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: devRepo     # ✅ Checkout code from GitHub repo

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build Next.js App'